### ISSUE TITLE
Unable to create cookie data

### ISSUE THREAD

**Issue by darkhelmet2016** [alzamer2/Crunchyroll-XML-Decoder-py3#12]
Traceback (most recent call last):
  File "C:\Users\Owner\Downloads\Crunchyroll-XML-Decoder-py3-master (2)\crunchy-
xml-decoder-py3.py", line 106, in <module>
    login('', '')
  File "crunchy-xml-decoder\login.py", line 125, in login
    userstatus = getuserstatus(False, sess_id_usa)
  File "crunchy-xml-decoder\login.py", line 29, in getuserstatus
    device_id = cookies_.get('COOKIES', 'device_id')
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\configparse
r.py", line 780, in get
    d = self._unify_values(section, vars)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\configparse
r.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'COOKIES'
Press any key to continue . . .

**Comment by Virusf** [comment]
I have the same problem
![Sans titre](https://user-images.githubusercontent.com/48204427/60421668-97074780-9bea-11e9-8011-548d5e36faf2.png)

**Comment by alzamer2** [comment]
Hmm
I think there error in lines order when he try to create new cookies file
Try copying old cookies file for now
I will look into it

**Comment by Virusf** [comment]
the problem is that I had not long ago the cookie file corrupted but ouf I had a backup
but if it happens to someone who has no backup
it will not work anymore

**Comment by Virusf** [comment]
ah now I have a problem with each reboot it passes in Guest without explanation and without error

**Comment by darkhelmet2016** [comment]
Had to redownload the package because was also getting an error trying to update.

python version=3.7.3 32 bit
OS Version=Windows 8.1 6.3.9600 SP0
System Type=AMD64
Code Version=1.2 rev.7 (Need to Update the Code)
Colorama : installed!
lxml : installed!
wget : installed!
Cryptography : installed!
Cfscrape : installed!
m3u8 : installed!
BeautifulSoup : installed!
pager : installed!
Unidecode : installed!
psutil : installed!
User Name = motokosuzumichan
Membership Type = Premium
Options:
1.- Download Anime
2.- Download Subtitle only
3.- Login
4.- Login As Guest
5.- Download an entire Anime(Autocatch links)
6.- Run Queue

111.- update
999.- Settings
000.- Exit
> 111
trying to close Crunchyroll-XML-Decoder-py3.......
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\psutil\_pswindows.py", line 716, in wrapper
Press any key to continue . . .     return fun(self, *args, **kwargs)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\psutil\_pswindows.py", line 790, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\crunchy-xml-decoder\updater.py", line 80, in <module>
    run_update()
  File ".\crunchy-xml-decoder\updater.py", line 66, in run_update
    close_code()
  File ".\crunchy-xml-decoder\updater.py", line 39, in close_code
    pInfoDict = proc.as_dict(attrs=['pid', 'name', 'cmdline'])
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\psutil\__init__.py", line 638, in as_dict
    ret = meth()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\psutil\__init__.py", line 790, in cmdline
    return self._proc.cmdline()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\psutil\_pswindows.py", line 718, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=12548)

**Comment by Virusf** [comment]
oh well I have no problem with creating cookies
updating their site may have corrected the problem

**Comment by Virusf** [comment]
I withdraw that I said it always bug

**Comment by alzamer2** [comment]
i think i found the problem, will update the code in git hub later for now change 
def create_sess_id_usa(params_v):
    usa_session = requests.session()
    sess_id_usa = ''
    usa_session_post = usa_session.post('http://api-manga.crunchyroll.com/cr_start_session', params=params_v)
    #print(usa_session_post.url)
    if usa_session_post.json()['error'] != "true":
        sess_id_usa = usa_session_post.json()['data']['session_id']
    if sess_id_usa=='':
        for prxy_ in get_proxy(['HTTPS'],['US']):
            proxies = {'https': prxy_}
            #print(proxies)
            try:
                usa_session_post = usa_session.post('https://api.crunchyroll.com/start_session.0.json', proxies=proxies,
                                                    params=params_v).json()
                sess_id_usa = usa_session_post['data']['session_id']
                return sess_id_usa
            except:
                pass

    return sess_id_usa

to 

def create_sess_id_usa(params_v):
    usa_session = requests.session()
    sess_id_usa = ''
    usa_session_post = usa_session.post('http://api-manga.crunchyroll.com/cr_start_session', params=params_v)
    #print(usa_session_post.url)
    if usa_session_post.json()['error'] != "true":
        sess_id_usa = usa_session_post.json()['data']['session_id']
    if sess_id_usa=='':
        for prxy_ in get_proxy(['HTTPS'],['US']):
            proxies = {'https': prxy_}
            #print(proxies)
            try:
                usa_session_post = usa_session.post('https://api.crunchyroll.com/start_session.0.json', proxies=proxies,
                                                    params=params_v).json()
                sess_id_usa = usa_session_post['data']['session_id']
                return sess_id_usa
            except:
                pass
        print('\x1b[31m'+'Could Not Create USA Session'+'\x1b[0m')
        print('\x1b[31m'+'You Will Not be Able to Download USA Locked Anime at Moment'+'\x1b[0m')
        print('\x1b[31m'+'Try Again Later'+'\x1b[0m')
        usa_session_post = usa_session.post('https://api.crunchyroll.com/start_session.0.json', params=params_v).json()
        sess_id_usa = usa_session_post['data']['session_id']

    return sess_id_usa

**Comment by alzamer2** [comment]
ok i updated the code
sorry for delay, i was not able to turn on my personal pc  these last 2 day, so i used my work pc to update the code (it has win xp and cant install gitub app so i used old git programe and needed time to find my way around it)

the problem was in creating usa session id code that will give you usa session no mater the country 
the code has many option to creat that session but you got that error if all method failed

plz test out the code and let me know if the problem solved

**Comment by Virusf** [comment]
little tested but I have everything seems to work

**Comment by darkhelmet2016** [comment]
Got this error but not sure if should open it as a new issue.
------------------------------
---- Downloading Subtitle ----
------------------------------
Attempting to download English (US) subtitle...
Starting mkv merge
Traceback (most recent call last):
  File "C:\Users\Owner\Downloads\Crunchyroll-XML-Decoder-py3-master (2)\crunchy-
xml-decoder-py3.py", line 407, in <module>
    make_choise()
  File "C:\Users\Owner\Downloads\Crunchyroll-XML-Decoder-py3-master (2)\crunchy-
xml-decoder-py3.py", line 376, in make_choise
    queueu(os.path.join('.','queue.txt'))
  File "C:\Users\Owner\Downloads\Crunchyroll-XML-Decoder-py3-master (2)\crunchy-
xml-decoder-py3.py", line 127, in queueu
    ultimate(line.rstrip('\n'), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 214, in ultimate
    mkv_merge(video_input, config_['video_quality'], 'English')
  File "crunchy-xml-decoder\ultimate.py", line 246, in mkv_merge
    if re.findall(r'\]\[(.*)\]',file)[0] == lang_iso[config_['language']]:
IndexError: list index out of range
Press any key to continue . . .
