### ISSUE TITLE
Wierd Download Error #2

### ISSUE THREAD

**Issue by reikitsune** [alzamer2/Crunchyroll-XML-Decoder-py3#13]
Seems I found another episode from a different series. This time from Yu-Gi-Oh!
From what I'm seeing, it's related to the previous issue to a certain extent, which means there's probably more errors like this, because of poor site maintenance on CR's part.
Episode Link: https://www.crunchyroll.com/yu-gi-oh/episode-31-brutal-heavy-metal-deck-691859

Error:
> Booting up...

Now Downloading - Yu-Gi-Oh! Episode 31 - Brutal * Heavy Metal Deck
Exception in thread download_thread_:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "crunchy-xml-decoder\hls_.py", line 95, in download_thread
    self.download_part(seg.absolute_uri, output, key, seg.media_sequence, self.tasks1)
  File "crunchy-xml-decoder\hls_.py", line 62, in download_part
    with open(filename, 'ab') as f_handle:
OSError: [Errno 22] Invalid argument: 'F:\\Crunchyroll-XML-Decoder-py3-master\\export\\Yu-Gi-Oh! Episode - 31 - Brutal * Heavy Metal Deck.ts0'

Traceback (most recent call last):
  File "F:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 407, in <module>
    make_choise()
  File "F:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 376, in make_choise
    queueu(os.path.join('.','queue.txt'))
  File "F:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 127, in queueu
    ultimate(line.rstrip('\n'), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 190, in ultimate
    download_.video_hls(hls_url, video_input, config_['connection_n_'])
  File "crunchy-xml-decoder\hls_.py", line 144, in video_hls
    self.fetch_streams()
  File "crunchy-xml-decoder\hls_.py", line 126, in fetch_streams
    os.rename(self.output+'0',self.output)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'F:\\Crunchyroll-XML-Decoder-py3-master\\export\\Yu-Gi-Oh! Episode - 31 - Brutal * Heavy Metal Deck.ts0' -> 'F:\\Crunchyroll-XML-Decoder-py3-master\\export\\Yu-Gi-Oh! Episode - 31 - Brutal * Heavy Metal Deck.ts'

**Comment by Virusf** [comment]
hello
at home I don't have a problem and it seems to me that the problem comes from the name 
but I modified in the files
 altfuncs.py
ultimate.py

on the last line of 

def clean_text(text_):

replaced all the code of this function by 

    return unidecode(re.sub(re.sub(r'[^A-Za-z0-9ÀÁÃÄÄÅÇÈÉÊËÌÍÎÎÏÒÓÔÕÖÙÚÚÛÜÝàáââããäåçèéêëìíîïðòóôóõööùúûüýÿ \t._-]+', ''', text_)

**Comment by reikitsune** [comment]
Alright, I've tried to chance the code to what you suggested, and it broke the program. I replace the original code, and started working again. Any idea why that happened?

**Comment by Virusf** [comment]
so here's the change. 

For altfuncs.py

`def clean_text(text_):
    ### Taken from http://stackoverflow.com/questions/6116978/python-replace-multiple-strings and improved to include the backslash###
    rep = {' / ': ' - ', '/': ' - ', ':': '-', '?': '.', '"': "''", '|': '-', '&quot;': "''", 'a*G': 'a G', '*': '#',
           r'\u2026': '...', r' \ ': ' - ', u'”': "''"}
    rep = dict((re.escape(k), v) for k, v in rep.items())
    pattern = re.compile("|".join(rep.keys()))
    return unidecode(pattern.sub(lambda m: rep[re.escape(m.group(0))], text_))`

By

`def clean_text(text_):
    return unidecode(re.sub(r'[^A-Za-z0-9ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïðòóôõöùúûüýÿ \t._-]+', '', text_))`

For ultimate.py

`def clean_text(text_):
    ### Taken from http://stackoverflow.com/questions/6116978/python-replace-multiple-strings and improved to include the backslash###
    rep = {' / ': ' - ', '/': ' - ', ':': '-', '?': '.', '"': "''", '|': '-', '&quot;': "''", 'a*G': 'a G', '*': '#',
           r'\u2026': '...', r' \ ': ' - ', u'”': "''"}
    rep = dict((re.escape(k), v) for k, v in rep.items())
    pattern = re.compile("|".join(rep.keys()))
    return unidecode(pattern.sub(lambda m: rep[re.escape(m.group(0))], text_))`

by

`def clean_text(text_):
    return unidecode(re.sub(r'[^A-Za-z0-9ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïðòóôõöùúûüýÿ \t._-]+', '', text_))`

**Comment by reikitsune** [comment]
There we go. Thanks @Virusf
