### ISSUE TITLE
error - hls_url IndexError

### ISSUE THREAD

**Issue by thekos1** [alzamer2/Crunchyroll-XML-Decoder-py3#17]
Hey there! Just tested your new rev. and this error keeps popping
![Capture](https://user-images.githubusercontent.com/58101507/69474723-fdc11380-0dcc-11ea-8bc1-c763f09efe21.JPG)

**Comment by alzamer2** [comment]
Can you post fill picture for your console
You can lank out your username

**Comment by thekos1** [comment]
Sure, here you go:
![Capture](https://user-images.githubusercontent.com/58101507/69478990-1a773e80-0e01-11ea-847b-0ead206e6857.JPG)

**Comment by alzamer2** [comment]
say do you have usa proxy option in setting true?

**Comment by alzamer2** [comment]
can you take picture for setting too

**Comment by alzamer2** [comment]
> python version=3.7.2 32 bit
OS Version=Windows 10 10.0.18362 SP0
System Type=AMD64
Code Version=1.3 rev.14 (Up-To-Date)
Colorama : installed!
lxml : installed!
wget : installed!
Cryptography : installed!
Cfscrape : installed!
m3u8 : installed!
youtube_dl : installed!
BeautifulSoup : installed!
pager : installed!
Unidecode : installed!
psutil : installed!
User Name = alzamer2
Membership Type = Free Member
  ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
  │                                                                                                                  │
  │  CrunchyRoll Downloader Toolkit                                                                                  │
  │                                                                                                                  │
  │  If you don't have a premium account, go and sign up for one now. It's well worth it, and supports the animators.│
  │                                                                                                                  │
  │    1 - Download Anime                                                                                            │
  │    2 - Download Subtitle only                                                                                    │
  │    3 - Login                                                                                                     │
  │    4 - Login As Guest                                                                                            │
  │    5 - Download an entire Anime(Autocatch links)                                                                 │
  │    6 - Run Queue                                                                                                 │
  │                                                                                                                  │
  │                                                                                                                  │
  │    999 - Settings                                                                                                │
  │                                                                                                                  │
  │                                                                                                                  │
  │    000 - Exit                                                                                                    │
  │                                                                                                                  │
  └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
>>1

--------------------------
---- Start New Export ----
--------------------------

CrunchyRoll Downloader Toolkit DX v0.98b

Crunchyroll hasn't changed anything.

If you don't have a premium account, go and sign up for one now. It's well worth it, and supports the animators.

----------
Booting up...

Please enter Crunchyroll video URL:
https://www.crunchyroll.com/one-piece/episode-865-dark-kings-direct-precepts-the-battle-against-katakuri-turns-around-778503
Now Downloading - One Piece Episode 865 - Dark King's Direct Precepts! The Battle Against Katakuri Turns Around!
                                             232MB/232MB                                             |%100 @ 8.00Mb/s
                                               Part#21                                               |%100.0
                                               Part#42                                               |%100.0
                                               Part#63                                               |%100.0
                                               Part#84                                               |%100.0
                                              Part#105                                               |%100.0
                                              Part#126                                               |%100.0
                                              Part#145                                               |%100.0


------------------------------
---- Downloading Subtitle ----
------------------------------
Attempting to download English (US) subtitle...
Attempting to download Português (Brasil) subtitle...
Attempting to download Español subtitle...
Starting mkv merge
mkvmerge v10.0.0 ('To Drown In You') 32bit
'C:\Users\Public\Crunchyroll-XML-Decoder_link\export\One Piece Episode - 865 - Dark King's Direct Precepts! The Battle Against Katakuri Turns Around!.ts': Using the demultiplexer for the format 'MPEG transport stream'.
'C:\Users\Public\Crunchyroll-XML-Decoder_link\export\One Piece Episode - 865 - Dark King's Direct Precepts! The Battle Against Katakuri Turns Around![eng][English (US)].ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'C:\Users\Public\Crunchyroll-XML-Decoder_link\export\One Piece Episode - 865 - Dark King's Direct Precepts! The Battle Against Katakuri Turns Around![por][Português (Brasil)].ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'C:\Users\Public\Crunchyroll-XML-Decoder_link\export\One Piece Episode - 865 - Dark King's Direct Precepts! The Battle Against Katakuri Turns Around![spa][Español].ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'C:\Users\Public\Crunchyroll-XML-Decoder_link\export\One Piece Episode - 865 - Dark King's Direct Precepts! The Battle Against Katakuri Turns Around!.ts' track 0: Using the output module for the format 'AVC/h.264 (unframed)'.
'C:\Users\Public\Crunchyroll-XML-Decoder_link\export\One Piece Episode - 865 - Dark King's Direct Precepts! The Battle Against Katakuri Turns Around!.ts' track 1: Using the output module for the format 'AAC'.
'C:\Users\Public\Crunchyroll-XML-Decoder_link\export\One Piece Episode - 865 - Dark King's Direct Precepts! The Battle Against Katakuri Turns Around![eng][English (US)].ass' track 0: Using the output module for the format 'text subtitles'.
'C:\Users\Public\Crunchyroll-XML-Decoder_link\export\One Piece Episode - 865 - Dark King's Direct Precepts! The Battle Against Katakuri Turns Around![por][Português (Brasil)].ass' track 0: Using the output module for the format 'text subtitles'.
'C:\Users\Public\Crunchyroll-XML-Decoder_link\export\One Piece Episode - 865 - Dark King's Direct Precepts! The Battle Against Katakuri Turns Around![spa][Español].ass' track 0: Using the output module for the format 'text subtitles'.
The file 'C:\Users\Public\Crunchyroll-XML-Decoder_link\export\One Piece Episode - 865 - Dark King's Direct Precepts! The Battle Against Katakuri Turns Around![480p].mkv' has been opened for writing.
'C:\Users\Public\Crunchyroll-XML-Decoder_link\export\One Piece Episode - 865 - Dark King's Direct Precepts! The Battle Against Katakuri Turns Around!.ts' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 853/480.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 7 seconds.
Merge process complete
Starting Final Cleanup
  ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
  │                                                                                                                  │
  │  CrunchyRoll Downloader Toolkit                                                                                  │
  │                                                                                                                  │
  │  If you don't have a premium account, go and sign up for one now. It's well worth it, and supports the animators.│
  │                                                                                                                  │
  │    1 - Download Anime                                                                                            │
  │    2 - Download Subtitle only                                                                                    │
  │    3 - Login                                                                                                     │
  │    4 - Login As Guest                                                                                            │
  │    5 - Download an entire Anime(Autocatch links)                                                                 │
  │    6 - Run Queue                                                                                                 │
  │                                                                                                                  │
  │                                                                                                                  │
  │    999 - Settings                                                                                                │
  │                                                                                                                  │
  │                                                                                                                  │
  │    000 - Exit                                                                                                    │
  │                                                                                                                  │
  └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
>>
![image](https://user-images.githubusercontent.com/4492974/69483812-a8205180-0e34-11ea-8e67-15d95b28ee58.png)
as you see it downloaded for me

**Comment by alzamer2** [comment]
by the way i tested it out with usa proxy option on false and i got same msg
you dont live in usa, right?

**Comment by thekos1** [comment]
Ahh true, with usa proxy works like a charm! Thx!

**Comment by thekos1** [comment]
Hi there!
After the recent token issue the above problem reappeared.
This time even if i have USA Proxy set to True i get the above exact error.
I'm only getting this error to titles that aren't available to my country (I'm outside US).

**Comment by alzamer2** [comment]
can you link the show you try to download from?

**Comment by thekos1** [comment]
sure, 
https://www.crunchyroll.com/one-piece/episode-912-the-strongest-man-in-the-world-shutenmaru-the-thieves-brigade-chief-790489

**Comment by alzamer2** [comment]
sorry for delay
i think i fixed it
delete your cookies file and re-login
tell me if it worked with you

**Comment by alzamer2** [comment]
sometimes ago i found a loophole that let me get usa session_id without any proxy
but umfortentuly it seem they found and fixe that loophole 
that why the usa option kept failing
