### ISSUE TITLE
Error with autocatch

### ISSUE THREAD

**Issue by fixx1983** [alzamer2/Crunchyroll-XML-Decoder-py3#19]
At the moment I press 5 for autocatc, before ask me for the serie link, the program gives me this error:

```
Traceback (most recent call last):
  File "H:\Crunchyroll-XML-Decoder-master\crunchy-xml-decoder-py3.py", line 645, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "H:\Crunchyroll-XML-Decoder-master\crunchy-xml-decoder-py3.py", line 536, in autocatch_t
    autocatch()
  File "crunchy-xml-decoder\altfuncs.py", line 371, in autocatch
    url = ''.join(re.findall(r'(https?://www\.crunchyroll\.com/)(?:[\w-]{2,5}/)?(.+?)(?=/|$)',url)[0])+'?skip_wall=1'
  File "C:\Python38\lib\re.py", line 239, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
```

**Comment by alzamer2** [comment]
can you tell me version of your code?
because i think i fexed this problem at 1.3 rev.14 i think

**Comment by fixx1983** [comment]
I'm on the latest one as far I know, thebprogram says in green that is the latest version

**Comment by fixx1983** [comment]
> can you tell me version of your code?
> ohh sorry i updated code but forgot to update version file so the code did not tell you to update

Ok, will give a look when I'm at home

**Comment by alzamer2** [comment]
sorry  i updated code but forgot to update version file so the code did not tell you to update
it seem you have rev 14
rev 15 fixed it, now when you get home the code will ask you to update

**Comment by fixx1983** [comment]
> sorry i updated code but forgot to update version file so the code did not tell you to update
> it seem you have rev 14
> rev 15 fixed it, now when you get home the code will ask you to update

Ok, will keep you informed about!

**Comment by fixx1983** [comment]
It works, thanks!

**Comment by alzamer2** [comment]
ok i'm closing this issue then
