### ISSUE TITLE
Proxies are not working

### ISSUE THREAD

**Issue by Dokman** [alzamer2/Crunchyroll-XML-Decoder-py3#2]
hello i am trying to download from USA from EU and i can't what's wrecked in the code? :(

**Comment by alzamer2** [comment]
which anime are you trying to download?

**Comment by Dokman** [comment]
High School DxD

**Comment by alzamer2** [comment]
hmm i just downloaded episode 0 without any problem
can you post me your settings?

**Comment by Dokman** [comment]
yes

# Set this to the preferred quality. Possible values are: "240p" , "360p", "480p", "720p", "1080p", or "highest" for highest available.
# Note that any quality higher than 360p still requires premium, unless it's available that way for free (some first episodes).
# We're not miracle workers.
video_quality = highest
# Set this to the desired subtitle language. If the subtitles aren't available in that language, it reverts to the second language option (below).
# Available languages: English, Espanol, Espanol_Espana, Francais, Portugues, Turkce, Italiano, Arabic, Deutsch
language = Espanol_Espana
# If the first language isn't available, what language would you like as a backup? Only if then they aren't found, then it goes to English as default
language2 = Espanol
# Set this if you want to use --forced-track rather than --default-track for subtitle
forcesubtitle = False
# Set this if you want to use a US session ID
forceusa = False
# Set this if you want to Localize the cookies (this option is under testing and may generate some problem and it willnot work with -forceusa- option)
localizecookies = False
# Set this if you only want to mux one subtitle only (this so make easy for some devices like TVs to play subtitle)
onlymainsub=False
# Set this option to increase the Number of the connection
connection_n_=1
# Set this option to use proxy, example: US
Proxy = US

**Comment by alzamer2** [comment]
forceusa = False
make this 
forceusa = True

**Comment by Dokman** [comment]
thank you i will test it now <3

**Comment by alzamer2** [comment]
can you post what you get here?

**Comment by alzamer2** [comment]
post all of it from the start

**Comment by Dokman** [comment]
![image](https://user-images.githubusercontent.com/2290904/56086695-d8465180-5e5c-11e9-9aa4-32686aa3ddd5.png)

**Comment by alzamer2** [comment]
ohh you are trying to autocatch

**Comment by Dokman** [comment]
yes hahahaha

**Comment by alzamer2** [comment]
say before i start anything
did you enable skip mature content from your account setting?

**Comment by Dokman** [comment]
where is that?

**Comment by alzamer2** [comment]
ok i fixed it i think
can you try it out?

**Comment by Dokman** [comment]
right now

**Comment by Dokman** [comment]
![image](https://user-images.githubusercontent.com/2290904/56087041-5f96c380-5e63-11e9-8c62-784737a09ca7.png)
Holyness is working

**Comment by alzamer2** [comment]
you can increase the number of connection in settings
and what do you think about new progress bar?

**Comment by Dokman** [comment]
i will tell you if subs are bad or someting
the new progress bar is well done
the connection number i will try it right now

**Comment by Dokman** [comment]
![image](https://user-images.githubusercontent.com/2290904/56087077-40e4fc80-5e64-11e9-8641-0df3c21d6255.png)

**Comment by alzamer2** [comment]
ok if every this is ok close this issue after you finish download ^^

**Comment by Dokman** [comment]
thanks
