### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by fixx1983** [alzamer2/Crunchyroll-XML-Decoder-py3#20]
If I try to login I receive this error

> Traceback (most recent call last):
>   File "H:\Crunchyroll-XML-Decoder-master\crunchy-xml-decoder-py3.py", line 113, in <module>
>     login(username, password)
>   File "crunchy-xml-decoder\login.py", line 112, in login
>     sess_id_usa = create_sess_id_usa(payload_usa)
>   File "crunchy-xml-decoder\login.py", line 155, in create_sess_id_usa
>     sess_id_usa = usa_session_post.json()['data']['session_id']
> KeyError: 'data'

I've no usa proxy or cookies enabled. Latest version.

**Comment by nigoki2** [comment]
Hi. Same issue with me :(

**Comment by Virusf** [comment]
I already noted them in issue  #16 
looked at the end

**Comment by alzamer2** [comment]
will look into it

**Comment by alzamer2** [comment]
it seem they changed access_token
i updated it
i think this should fix this issue

**Comment by nigoki2** [comment]
It works. Thank you very much  alzamer2.

**Comment by fixx1983** [comment]
works, thanks!
