### ISSUE TITLE
Suggestion: MKVmerge Update

### ISSUE THREAD

**Issue by ch4d1** [alzamer2/Crunchyroll-XML-Decoder-py3#21]
MKVmerge should be updated and 64-Bit systems should use the 64-Bit Version as the speed improvements are significant

**Comment by alzamer2** [comment]
i can update mkvmerger
but about 32/64 bit, i use 32bit because it work in both system
and i'm not sure if python 32bit can run 64bit programs even in system is 64bit

**Comment by ch4d1** [comment]
Actually i didn't notice, that i was running 32-bit python on my 64-bit system. So yeah, it seams to work.

But i guess the real problem would be to detect if the system is 64-bit, even if python is running in 32-bit. But maybe, just maybe, it would be enough to just detect whether python is running in 64-bit or not. So that people which installed the correct version of python would benefit from it :)

import platform
platform.architecture()[0] # '64-bit'

**Comment by alzamer2** [comment]
as i already updated mkvmerger I will close this issue
