### ISSUE TITLE
Stopped working after latest update

### ISSUE THREAD

**Issue by fixx1983** [alzamer2/Crunchyroll-XML-Decoder-py3#23]
After latest update the progrma will not start. It print this:

```
python version=3.8.0 64 bit
OS Version=Windows 10 10.0.18362 SP0
System Type=AMD64
Code Version=1.3 rev.17 (Up-To-Date)
Colorama : installed!
lxml : installed!
wget : installed!
Cryptography : installed!
Cfscrape : installed!
m3u8 : installed!
youtube_dl : installed!
BeautifulSoup : installed!
pager : installed!
Unidecode : installed!
psutil : installed!
```
and it does nothing else.

**Comment by alzamer2** [comment]
@fixx1983 about this, its because its trying to create us seeson id
the loophole i used to use was fixed , so i'm using proxy to get that seesion,

**Comment by fixx1983** [comment]
So it's only matter of time? After a while it started

**Comment by alzamer2** [comment]
yes

**Comment by fixx1983** [comment]
Ok, thanks a lot

**Comment by alzamer2** [comment]
this script look and found proxy, but some of these proxy dont work or has high latency so the script stuck at them for long time, that where you get stuck
