### ISSUE TITLE
Special characters preventing download

### ISSUE THREAD

**Issue by darkhelmet2016** [alzamer2/Crunchyroll-XML-Decoder-py3#24]
Booting up...

Now Downloading - Re-ZERO -Starting Life in Another World- Episode 9 - "The Gree
d of a Pig - Disgrace in the Extreme
Exception in thread download_thread_:
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\threading.p
y", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\threading.p
y", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "crunchy-xml-decoder\hls_.py", line 95, in download_thread
    self.download_part(seg.absolute_uri, output, key, seg.media_sequence, self.t
asks1)
  File "crunchy-xml-decoder\hls_.py", line 62, in download_part
    with open(filename, 'ab') as f_handle:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Owner\\Downloads\\Crunchyroll-
XML-Decoder-py3-master\\export\\Re-ZERO -Starting Life in Another World- Episode
 - 9 - "The Greed of a Pig - Disgrace in the Extreme.ts0'

Traceback (most recent call last):
  File "C:\Users\Owner\Downloads\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-
decoder-py3.py", line 645, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "C:\Users\Owner\Downloads\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-
decoder-py3.py", line 143, in queueu
    ultimate(line.strip(), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 213, in ultimate
    download_subprocess_result = download_.video_hls(hls_url, video_input, confi
g_['connection_n_'])
  File "crunchy-xml-decoder\hls_.py", line 162, in video_hls
    self.fetch_streams()
  File "crunchy-xml-decoder\hls_.py", line 126, in fetch_streams
    os.rename(self.output+'0',self.output)
OSError: [WinError 123] The filename, directory name, or volume label syntax is
incorrect: 'C:\\Users\\Owner\\Downloads\\Crunchyroll-XML-Decoder-py3-master\\exp
ort\\Re-ZERO -Starting Life in Another World- Episode - 9 - "The Greed of a Pig
- Disgrace in the Extreme.ts0' -> 'C:\\Users\\Owner\\Downloads\\Crunchyroll-XML-
Decoder-py3-master\\export\\Re-ZERO -Starting Life in Another World- Episode - 9
 - "The Greed of a Pig - Disgrace in the Extreme.ts'
Press any key to continue . . .

**Comment by nigoki2** [comment]
I have the same issue with "«" and "»".

**Comment by alzamer2** [comment]
@nigoki2 
can you give me link you used, i'm working on this issue atm

**Comment by nigoki2** [comment]
@alzamer2
Sure: https://www.crunchyroll.com/fr/one-piece/episode-24-hawk-eye-mihawk-the-great-swordsman-zoro-falls-at-sea-650719

**Comment by alzamer2** [comment]
ok
@nigoki2 i think i fixed it
as for @darkhelmet2016 if the link that you tried to download was https://www.crunchyroll.com/rezero-starting-life-in-another-world-/episode-9-the-greed-of-a-pig-disgrace-in-the-extreme-793679 then i think i fixed that too, if not can you post the link that dont work for you?

**Comment by b955** [comment]
@alzamer2 i have the same problem in here 
https://www.crunchyroll.com/relife/episode-7-test-subject-001-002-714865

**Comment by alzamer2** [comment]
Try now Sent from Mail for Windows 10 From: b955Sent: Wednesday, March 25, 2020 5:54 PMTo: alzamer2/Crunchyroll-XML-Decoder-py3Cc: alzamer2; MentionSubject: Re: [alzamer2/Crunchyroll-XML-Decoder-py3] Special characters preventing download (#24) @alzamer2 i have the same problem in herehttps://www.crunchyroll.com/relife/episode-7-test-subject-001-002-714865—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by b955** [comment]
@alzamer2 it works now , Thanks

**Comment by nigoki2** [comment]
@alzamer2 same here, thank you very much!

**Comment by alzamer2** [comment]
only @darkhelmet2016 link left
but let's not close this issue to add any new character in future

**Comment by darkhelmet2016** [comment]
It works but is there a way to remove the quotations from the title since they have a bad habit of screwing up like this a lot.

**Comment by alzamer2** [comment]
no can do
each character must add separately because each font has its own Special characters and must work on these case by case

**Comment by darkhelmet2016** [comment]
Actually it should be, looking at the code it has a section where you have characters replaced in the header like / or \ in names, and it was possible before in older versions unless you changed it because it was possible before.

**Comment by alzamer2** [comment]
the code still there just moved it to altfunc.py
but as i said each font had its own Special characters, for example https://www.crunchyroll.com/rezero-starting-life-in-another-world-/episode-9-the-greed-of-a-pig-disgrace-in-the-extreme-793679 , use “ instead of "
