### ISSUE TITLE
Exception in thread compute_total_size_thread_

### ISSUE THREAD

**Issue by Askadelion** [alzamer2/Crunchyroll-XML-Decoder-py3#26]
This error come when i try to download.

----------
Booting up...

Please enter Crunchyroll video URL:
https://www.crunchyroll.com/de/ascendance-of-a-bookworm/episode-21-new-retainers-794557
Now Downloading - Ascendance of a Bookworm Episode 21
Exception in thread compute_total_size_thread_: 124MB                                                |    @ 14.07Mb/s
Traceback (most recent call last):             Part#12                                               |%6.73
  File "C:\Python37-32\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Python37-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "crunchy-xml-decoder\hls_.py", line 46, in compute_total_size
    self.compute_total_size_part(video[n].absolute_uri, str(video[n].media_sequence))
  File "crunchy-xml-decoder\hls_.py", line 34, in compute_total_size_part
    self.part_size[n] = response.headers['Content-Length']
  File "C:\Python37-32\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'

**Comment by Askadelion** [comment]
now come the error ^^"

cloudscraper.exceptions.CloudflareReCaptchaProvider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.

**Comment by alzamer2** [comment]
sorry i'm working on other problem
but can you post me a full text from what shows up in consol?

**Comment by Askadelion** [comment]
i have instal the update to 1.3 rev.22
now i become the error:
cloudscraper.exceptions.CloudflareReCaptchaProvider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.

![ss (2020-05-31 at 01 07 27)](https://user-images.githubusercontent.com/41443013/83340735-270eaf00-a2dc-11ea-9187-4405ee0a2a3b.png)

![ss (2020-05-31 at 01 08 47)](https://user-images.githubusercontent.com/41443013/83340738-2a099f80-a2dc-11ea-9dc8-b66d5a759611.png)

![ss (2020-05-31 at 01 09 16)](https://user-images.githubusercontent.com/41443013/83340681-71dbf700-a2db-11ea-9409-aa1075449cff.png)

cfscrape is 2.1.1
node is v13.13.0

i think now is it the same error with here xD
https://github.com/alzamer2/Crunchyroll-XML-Decoder-py3/issues/27

**Comment by alzamer2** [comment]
i already closed #27 so i will close this 1 too
