### ISSUE TITLE
Issue after inserting the episode url

### ISSUE THREAD

**Issue by fixx1983** [alzamer2/Crunchyroll-XML-Decoder-py3#27]
As said the program gives me back this issue:
```
Traceback (most recent call last):
  File "I:\Crunchyroll-XML-Decoder-master\crunchy-xml-decoder-py3.py", line 645, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "crunchy-xml-decoder\ultimate.py", line 95, in ultimate
    htmlconfig = json.loads(re.findall(r'vilos\.config\.media = ({.*})',html_page_)[0])
IndexError: list index out of range
```

Found this issue https://github.com/alzamer2/Crunchyroll-XML-Decoder-py3/issues/22
but there isn't any solution

**Comment by Virusf** [comment]
ah i'm not alone anymore and i have already raised the problem in issue #16

**Comment by nigoki2** [comment]
Same here.

**Comment by alzamer2** [comment]
not sure if its same issue as @Virusf in #16 
but can you try doing same as @Virusf or wait and see if fixing @Virusf issue will fix yours too

**Comment by alzamer2** [comment]
on side note 
can you post the link you used to download so i can paste and test it out

**Comment by nigoki2** [comment]
Hi  alzamer2.

https://www.crunchyroll.com/fr/major-2nd/episode-5-girl-power-baseball-style-794569

I'm a premium member, and the free episodes don't work as well.

**Comment by alzamer2** [comment]
hi @Virusf  and @nigoki2 
i want both of you tests something for me
open cmd
 then type :
```
pip show cfscrape
node -v
```
after that post what you get on consel here

**Comment by fixx1983** [comment]
> on side note
> can you post the link you used to download so i can paste and test it out

https://www.crunchyroll.com/it/tower-of-god/episode-9-the-one-horned-ogre-794527

**Comment by alzamer2** [comment]
@fixx1983 i want you tests something for me
open cmd
 then type :
```
pip show cfscrape
node -v
```
after that post what you get on consel here

**Comment by fixx1983** [comment]
Will be at home in 15 minutes more or less

**Comment by nigoki2** [comment]
For me pip show cfscrape doesn't work.

node -v -> v6.11.2

**Comment by Virusf** [comment]
this is what i have
![Sans titre](https://user-images.githubusercontent.com/48204427/83337335-abe8d100-a2ba-11ea-942e-0060d2bea978.png)

and by modifying the code with a print before the error and here is the result
![print](https://user-images.githubusercontent.com/48204427/83337524-6c22e900-a2bc-11ea-800a-ad5603b74170.png)
![resul](https://user-images.githubusercontent.com/48204427/83337526-6fb67000-a2bc-11ea-9262-cced484b179c.png)

**Comment by alzamer2** [comment]
hmm from this msg i'm sure its CF issue, it seem they updated the code again

**Comment by alzamer2** [comment]
i will look for other cf scraper

**Comment by fixx1983** [comment]
for me it says the same for cfscrape, but says that node is not a valid command

**Comment by alzamer2** [comment]
the code use scscraper
and that scscraper need node v10 or newer to work
but in any cases, it seems CF updated their page so it does not work
as you see @Virusf  got all condition ok but still have the same CF issue

**Comment by alzamer2** [comment]
ok i changed CF scraper
try it out and tell me if it worked

**Comment by fixx1983** [comment]
> ok i changed CF scraper
> try it out and tell me if it worked

`cloudscraper.exceptions.CloudflareReCaptchaProvider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.`

**Comment by Virusf** [comment]
I had python which had errors, after more error and the program works very well after the 1st test

**Comment by Askadelion** [comment]
> 
> 
> > ok i changed CF scraper
> > try it out and tell me if it worked
> 
> `cloudscraper.exceptions.CloudflareReCaptchaProvider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.`

i have the same error, now

**Comment by jsonn** [comment]
Check that your Python installation uses OpenSSL 1.1, i.e. has support for TLS 1.3:
```
import ssl
print(ssl.OPENSSL_VERSION)
```
Without TLS 1.3 support, Cloudfare will enable the CAPTCHA.

**Comment by Askadelion** [comment]
![ss (2020-06-02 at 06 11 48)](https://user-images.githubusercontent.com/41443013/83543399-9cf16100-a4fc-11ea-95da-0dad0d71c04d.png)

this?

**Comment by alzamer2** [comment]
to update ssl, just dowbload and insyall lastest python 3.7.x

**Comment by Askadelion** [comment]
you mean 3.7.7?

**Comment by alzamer2** [comment]
yes
OpenSSL is internal lib so to upgrade it you need to upgrade python

**Comment by alzamer2** [comment]
test it out for me
as i don't get Cloudflare page so I cant test it out

**Comment by Askadelion** [comment]
nöp, same error

Please enter Crunchyroll video URL:
https://www.crunchyroll.com/de/princess-connect-re-dive/episode-9-a-gourmet-getaway-fragrant-tentacles-on-the-beach-794695
cloudscraper.exceptions.CloudflareReCaptchaProvider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.

**Comment by fixx1983** [comment]
Tried to rollback to 3.7.7. Not working for me too, same error

**Comment by Askadelion** [comment]
i have today try again:
i have upgrade my npm & node 

![node](https://user-images.githubusercontent.com/41443013/83722185-d5985400-a63c-11ea-9c53-4026a90db113.PNG)

after upgrade i have new errors the video is downloadet but at the download from the subtitle come now this

![try2](https://user-images.githubusercontent.com/41443013/83722381-27d97500-a63d-11ea-8bcf-84f528293842.PNG)

**Comment by b955** [comment]
> i have today try again:
> i have upgrade my npm & node
> 
> ![node](https://user-images.githubusercontent.com/41443013/83722185-d5985400-a63c-11ea-9c53-4026a90db113.PNG)
> 
> after upgrade i have new errors the video is downloadet but at the download from the subtitle come now this
> 
> ![try2](https://user-images.githubusercontent.com/41443013/83722381-27d97500-a63d-11ea-8bcf-84f528293842.PNG)

no its just when you try to download in another day it works but just one file and then the problem is back so thats why the episode downloaded but the sub not

**Comment by alzamer2** [comment]
not sure if that fixed it, but try new update

**Comment by b955** [comment]
> not sure if that fixed it, but try new update

Yes it works now Thanks a lot .

**Comment by b955** [comment]
> not sure if that fixed it, but try new update

it's working but still the reCaptcha problem show up sometimes (*_*)

**Comment by Askadelion** [comment]
its a block, when u wait 15~20 min than working it again.
