### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by darkhelmet2016** [alzamer2/Crunchyroll-XML-Decoder-py3#28]
Command python setup.py egg_info failed with error code 1 in C:\Users\Owner\AppD
ata\Local\Temp\pip_build_Owner\lxml
Storing debug log for failure in C:\Users\Owner\pip\pip.log
Traceback (most recent call last):
  File "C:\Users\Owner\Desktop\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-de
coder-py3.py", line 33, in <module>
    testing_external_moudules_(code_version)
  File "crunchy-xml-decoder\external_test.py", line 150, in testing_external_mou
dules_
    import wget
ImportError: No module named 'wget'
Press any key to continue . . .

**Comment by Isis45** [comment]
I think you should install the necessary libs required.
(pip install requirements.txt)

**Comment by alzamer2** [comment]
try running code again
some times in the first run error happen because some lib just installed
so after first run it should have been fixed
