### ISSUE TITLE
Premium login broken

### ISSUE THREAD

**Issue by darkhelmet2016** [alzamer2/Crunchyroll-XML-Decoder-py3#29]
Traceback (most recent call last):
  File "C:\Users\Owner\Desktop\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-de
coder-py3.py", line 645, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "C:\Users\Owner\Desktop\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-de
coder-py3.py", line 522, in login_t
    userstatus = login(username, password)
  File "crunchy-xml-decoder\login.py", line 117, in login
    sess_id_usa = create_sess_id_usa(payload_usa)
  File "crunchy-xml-decoder\login.py", line 176, in create_sess_id_usa
    if usa_session_post.json()['error'] != "true":
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\json\__init
__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\json\decode
r.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\json\decode
r.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Press any key to continue . . .

**Comment by Virusf** [comment]
it is true that I have to launch the program 4 times see more to have the connection to my account

**Comment by nigoki2** [comment]
@Virusf And your downloads start ?

**Comment by Virusf** [comment]
If the login passes the rest of the program works fine

**Comment by darkhelmet2016** [comment]
But you still need a functioning log in to download certain content if it has the premiere icon next to it.

**Comment by nigoki2** [comment]
Most of my downloads are broken: the files are muxed but the episodes are incomplete.

**Comment by alzamer2** [comment]
its working fine for me
from some time ago the script keeps failing because of new Cloudflare the crunchy use
because my ip not in blacklist of Cloudflare icant test it out TT

**Comment by alzamer2** [comment]
can you try something for me?
aat line 176 add 
```
print(usa_session_post.status_code)
print(usa_session_post.content)
```
i want to see what msg shows up to you

**Comment by Virusf** [comment]
in which file it is to do?

**Comment by alzamer2** [comment]
"crunchy-xml-decoder\login.py"

**Comment by Virusf** [comment]
good as i managed to connect today i have more problem for the moment

**Comment by alzamer2** [comment]
like what?

**Comment by Virusf** [comment]
when i want to use the program, i have to launch it 4 to 5 times for the login to work.
and when it works there is more problem.
sorry it's not easy explained.

**Comment by alzamer2** [comment]
can you give me picture of what error you get
and if it same as @darkhelmet2016 add 
```
print(usa_session_post.status_code)
print(usa_session_post.content)
```
at line 176  befoer you run program

**Comment by Virusf** [comment]
when i want to use the program, i have to launch it 4 to 5 times for the login to work.
and when it works there is more problem.
sorry it's not easy explained.

**Comment by alzamer2** [comment]
lol

**Comment by alzamer2** [comment]
the main problem I have atm is that script/program is working fine for me
that why I cant track down the error that you get
I need the feedback of 
```
print(usa_session_post.status_code)
print(usa_session_post.content)
```
to look for error at least

**Comment by Virusf** [comment]
here I had 3 times the following errors
![error](https://user-images.githubusercontent.com/48204427/84800711-7a803d00-affe-11ea-8251-a3b91aee9864.png)
and I also added
print ('Test Login Error')
to find out when he had a login error
therefore normal the Test Login Error

**Comment by alzamer2** [comment]
hmm
i'm using google service to produce usa session
maybe I need to optimize the code

**Comment by Virusf** [comment]
and being in another country is not a problem?
stupid question but in case I say it

**Comment by alzamer2** [comment]
i made the code generate 2 see_id whn it log in
1 for your country and other 1 fixed for US(a lot of anime need to be in US/CA zone to unlocked)

**Comment by Virusf** [comment]
OK OK thank you for the reply

**Comment by alzamer2** [comment]
lol it seem i used site key word and closed it when i uploaded lastest patch
@Virusf , @darkhelmet2016 
i updated the code
now it will not try to generate sess_id fixed to us if you are already in us or your "USA Proxy" option is False
try it and tell me wht you get

**Comment by Virusf** [comment]
I tested all day and unable to connect.
but with the modification, it is directly connected
so it works very well

**Comment by alzamer2** [comment]
@Virusf 
you live in usa?

**Comment by Virusf** [comment]
no in europe

**Comment by alzamer2** [comment]
ohh
do you have USA Proxy at True?

**Comment by Virusf** [comment]
no
why it matters because i never used that

**Comment by alzamer2** [comment]
lol
before it did not matter but now it do
before this patch
the script generate 2 sess_id
1 in for your country 
and other for USA
because a most of crunchyroll anime unlocked in USA
and to make it faster it will generate these 2 sess_id and store them
now it will only generate your country sess_id and unless you have "USA Proxy" option True it will not generate Sess_Id fix for usa (unless you already in usa as this will ignore this option)

**Comment by Virusf** [comment]
after as i take that what is translated in my country
I do not have any problems

**Comment by alzamer2** [comment]
nice
i want you to try to change "USA Proxy" option to True and test it for me
you can later change it to false
i just need some feedback

**Comment by Virusf** [comment]
I got this "using g_proxy retry # 1"

**Comment by alzamer2** [comment]
it should stay there like up to 5min

**Comment by alzamer2** [comment]
after that it will if google proxy did not wotk it will switch to other method

**Comment by Virusf** [comment]
voilà ce que j'ai
![test](https://user-images.githubusercontent.com/48204427/84942760-a0334200-b0e3-11ea-9505-d030aa85f30d.png)
et ca ne bouge plus

**Comment by alzamer2** [comment]
now its trying the second method

**Comment by Virusf** [comment]
this is very very long

**Comment by alzamer2** [comment]
lol
even if it take too long i need this usa sess id XD

**Comment by Virusf** [comment]
sorry but i will do that tomorrow because there is more time to do it

**Comment by alzamer2** [comment]
iok thanks for testing it out for me
you can change the option from outide in"settings.ini" forceusa

**Comment by nigoki2** [comment]
@alzamer2 I don't know what you changed, but now it works perfectly for me.
Thank you very much!

**Comment by Virusf** [comment]
@alzamer2 I retested your request and the login went well
so my question you need what as info after ?

**Comment by alzamer2** [comment]
thanks @Virusf 
i just to test it to find if it work for other not only for my self
