### ISSUE TITLE
Subtitle download error

### ISSUE THREAD

**Issue by lazerbeakravage** [alzamer2/Crunchyroll-XML-Decoder-py3#37]
Hi 

I am trying to download this anime but this season seems to be erroring.  Other seasons seem to be ok.  

Anime:  http://www.crunchyroll.com/a-certain-scientific-railgun/episode-1-railgun-727295

> python version=3.8.5 64 bit
OS Version=Linux 5.4.0 52 generic x86_64 with glibc2.29
System Type=x86_64
Code Version=1.3 rev.28 (Up-To-Date)
Colorama : installed!
lxml : installed!
wget : installed!
Cryptography : installed!
cloudscraper : installed!
m3u8 : installed!
youtube_dl : installed!
BeautifulSoup : installed!
pager : installed!
Unidecode : installed!
psutil : installed!
Login as **** successfully.

> Attempting to download English (US) subtitle...
Starting mkv merge
mkvmerge v47.0.0 ('Black Flag') 64-bit
Error: The type of file '/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 1 - Railgun.ts' could not be recognized.
Merge process complete
Starting Final Cleanup

**Comment by alzamer2** [comment]
hi after testing, i found out the problem is in mkvmerger
the mepg-ts(.ts) file downloaded from site is without pat/pmt which new version of mkvmerger give you error
use ver 10 at https://github.com/alzamer2/Crunchyroll-XML-Decoder-py3/releases/download/v0.0/mkvmerge.zip for now untill i fix it

**Comment by lazerbeakravage** [comment]
That works.  Thank you!

**Comment by alzamer2** [comment]
ok try deleting mkvmerger and try new update

**Comment by lazerbeakravage** [comment]
That looks like it works.  Although I'm not sure what to make of the output. (I think it looks fine)

Thank you!

>Attempting to download English (US) subtitle...
Starting mkv merge
mkvmerge v51.0.0 ('I Wish') 64-bit
Error: The type of file '/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party.ts' could not be recognized.
fixing TS file
ffmpeg version 4.3.1-2020-11-02-essentials_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.0 (Rev3, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec
--enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mpegts @ 0000000000378840] start time for stream 2 is not set in estimate_timings_from_pts
Input #0, mpegts, from '/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party.ts':
  Duration: 00:23:57.77, start: 0.101000, bitrate: 6633 kb/s
  Program 1
    Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn,
47.95 tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 131 kb/s
    Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Output #0, mpegts, to '/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party_fix.ts':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 131 kb/s
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
Press [q] to stop, [?] for help
frame=34470 fps=1250 q=-1.0 Lsize= 1166708kB time=00:23:57.75 bitrate=6647.6kbits/s speed=52.1x
video:1109551kB audio:22889kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.026039%
mkvmerge v51.0.0 ('I Wish') 64-bit
'/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party_fix.ts': Using the demultiplexer for the format 'MPEG transport stream'.
'/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party[eng][English (US)].ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party_fix.ts' track 0: Using the output module for the format 'AVC/H.264 (unframed)'.
'/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party_fix.ts' track 1: Using the output module for the format 'AAC'.
'/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party[eng][English (US)].ass' track 0: Using the
output module for the format 'text subtitles'.
The file '/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party[highest].mkv' has been opened for
writing.
'/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party_fix.ts' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 1920/1080.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 54 seconds.
Merge process complete
Starting Final Cleanup

**Comment by alzamer2** [comment]
new mkvmerger cant mux ts file without PAT index ( the old mkvmerger [v10] ignor pat index)
some crunchyroll ts files dont have that index that why mkvmerger  might give "Error: The type of file ... could not be recognized."
i found round way to fix gthat problem by using ffmpeg.exe to re-builed ts file to add index to it
as for the output it goes as :

this part 

> Attempting to download English (US) subtitle...
Starting mkv merge
mkvmerge v51.0.0 ('I Wish') 64-bit
Error: The type of file '/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party.ts' could not be recognized.

tell you that there is problem with TS file aka there is no pat index

as for this part

> fixing TS file
ffmpeg version 4.3.1-2020-11-02-essentials_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 10.2.0 (Rev3, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec
--enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
libavutil 56. 51.100 / 56. 51.100
libavcodec 58. 91.100 / 58. 91.100
libavformat 58. 45.100 / 58. 45.100
libavdevice 58. 10.100 / 58. 10.100
libavfilter 7. 85.100 / 7. 85.100
libswscale 5. 7.100 / 5. 7.100
libswresample 3. 7.100 / 3. 7.100
libpostproc 55. 7.100 / 55. 7.100
[mpegts @ 0000000000378840] start time for stream 2 is not set in estimate_timings_from_pts
Input #0, mpegts, from '/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party.ts':
Duration: 00:23:57.77, start: 0.101000, bitrate: 6633 kb/s
Program 1
Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn,
47.95 tbc
Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 131 kb/s
Stream #0:2[0x102]: Data: timed_id3 (ID3 / 0x20334449)
Output #0, mpegts, to '/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party_fix.ts':
Metadata:
encoder : Lavf58.45.100
Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 131 kb/s
Stream #0:2: Data: timed_id3 (ID3 / 0x20334449)
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #0:1 -> #0:1 (copy)
Stream #0:2 -> #0:2 (copy)
Press [q] to stop, [?] for help
frame=34470 fps=1250 q=-1.0 Lsize= 1166708kB time=00:23:57.75 bitrate=6647.6kbits/s speed=52.1x
video:1109551kB audio:22889kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.026039%

its about using ffmpeg.exe to re-build the ts file

finaly fo r this part :

> mkvmerge v51.0.0 ('I Wish') 64-bit
'/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party_fix.ts': Using the demultiplexer for the format 'MPEG transport stream'.
'/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party[eng][English (US)].ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party_fix.ts' track 0: Using the output module for the format 'AVC/H.264 (unframed)'.
'/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party_fix.ts' track 1: Using the output module for the format 'AAC'.
'/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party[eng][English (US)].ass' track 0: Using the
output module for the format 'text subtitles'.
The file '/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party[highest].mkv' has been opened for
writing.
'/home/root/Crunchyroll-XML-Decoder-py3/export/A Certain Scientific Railgun Episode - 24 - Eternal Party_fix.ts' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 1920/1080.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 54 seconds.
Merge process complete
Starting Final Cleanup

its trying to mux again with new mkvmerger

**Comment by lazerbeakravage** [comment]
Thank you for the explanation!

It's working well again so this can be closed.
