### ISSUE TITLE
Incorrect time length after mkvmerge

### ISSUE THREAD

**Issue by lazerbeakravage** [alzamer2/Crunchyroll-XML-Decoder-py3#38]
Hi,

Only seeing this on random episodes but some episodes are getting merged with a few extra minutes.  The downloaded .ts file has the correct length prior to mkvmerge.  I notice this on mkvmerge v10 and 47(x64).

Anime: http://www.crunchyroll.com/fatekaleid-liner-prisma-illya/episode-6-blue-glass-moon-682409

Fate - kaleid liner PRISMA ILLYA Episode - 6 - Blue Glass Moon.ts                              00:23:35
Fate - kaleid liner PRISMA ILLYA Episode - 6 - Blue Glass Moon[highest].mkv                    00:25:35

> Attempting to download English (US) subtitle...
Starting mkv merge
mkvmerge v10.0.0 ('To Drown In You') 32bit
'/home/root/Crunchyroll-XML-Decoder-py3/export/Fate - kaleid liner PRISMA ILLYA Episode - 6 - Blue Glass Moon.ts': Using the demultiplexer for the format 'MPEG transport stream'.
'/home/root/Crunchyroll-XML-Decoder-py3/export/Fate - kaleid liner PRISMA ILLYA Episode - 6 - Blue Glass Moon[eng][English (US)].ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'/home/root/Crunchyroll-XML-Decoder-py3/export/Fate - kaleid liner PRISMA ILLYA Episode - 6 - Blue Glass Moon.ts' track 0: Using the output module for the format 'AVC/h.264 (unframed)'.
'/home/root/Crunchyroll-XML-Decoder-py3/export/Fate - kaleid liner PRISMA ILLYA Episode - 6 - Blue Glass Moon.ts' track 1: Using the output module for the format 'AAC'.
'/home/root/Crunchyroll-XML-Decoder-py3/export/Fate - kaleid liner PRISMA ILLYA Episode - 6 - Blue Glass Moon[eng][English (US)].ass' track 0: Using the output module for the format 'text subtitles'.
The file '/home/root/Crunchyroll-XML-Decoder-py3/export/Fate - kaleid liner PRISMA ILLYA Episode - 6 - Blue Glass Moon[highest].mkv' has been opened for writing.
'/home/root/Crunchyroll-XML-Decoder-py3/export/Fate - kaleid liner PRISMA ILLYA Episode - 6 - Blue Glass Moon.ts' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 1920/1080.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 1 minute 36 seconds.
Merge process complete
Starting Final Cleanup

**Comment by alzamer2** [comment]
the problem is not in code or mkvmerger
when mkvmerger mux the ts file (video+audio) and subtitle, the result mkv time length will be to the longest track
I downloaded the subtitles of the episode and found the next episode  title go to 00:25:35, that why mkv length is 00:25:35

**Comment by lazerbeakravage** [comment]
Thanks for looking into it!

Closing as this is a non issue.
