### ISSUE TITLE
I can't run the script.

### ISSUE THREAD

**Issue by nigoki2** [alzamer2/Crunchyroll-XML-Decoder-py3#4]
After insalling Node.js I got this:

Traceback (most recent call last):
  File "D:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 26, in <module>
    from updater import get_lastest_version, run_update
  File "crunchy-xml-decoder\updater.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Appuyez sur une touche pour continuer...

**Comment by alzamer2** [comment]
i updated the code
can you test it out?

**Comment by alzamer2** [comment]
@nigoki2
Did it work out?

**Comment by nigoki2** [comment]
@alzamer2 Yes and it works perfectly! Thank you very much!

**Comment by alzamer2** [comment]
OK I will close this issue then
If you needed any thing else open new issue
