### ISSUE TITLE
[Bug] Downloading with latest 1.4

### ISSUE THREAD

**Issue by Dokman** [alzamer2/Crunchyroll-XML-Decoder-py3#48]
Everytime i try to download i am having the same issue

`KeyError: 'session_id'`

![image](https://user-images.githubusercontent.com/2290904/138976451-e569bacf-c0ea-4708-b202-413d800ad1c4.png)
![image](https://user-images.githubusercontent.com/2290904/139025207-e374ce9d-f851-4522-b9e2-34e1a43265b3.png)
![image](https://user-images.githubusercontent.com/2290904/139026115-869336d5-df0a-4717-b459-3deb50a1aa47.png)

**Comment by alzamer2** [comment]
Is this new 1.4?

**Comment by Dokman** [comment]
Yes, latest 1.4 branch

**Comment by alzamer2** [comment]
1.4 rev.32 is up and it should fix this problem

the problem is in new feature but its still under testing
if the problem stay up, you can pass it by simply going to chrome browser and log in to your crunchyroll account there

**Comment by reikitsune** [comment]
I keep getting this from a clean install:

Booting up...
Please enter Crunchyroll video URL:>
https://www.crunchyroll.com/digimon-ghost-game/episode-1-the-sewn-lip-man-816959
Traceback (most recent call last):
  File "crunchy-xml-decoder-py3.py", line 402, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 128, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 155, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "crunchy-xml-decoder-py3.py", line 134, in ultimate_
    ultimate_class.download(*arg,**kwarg)
  File "crunchy-xml-decoder\ultimate.py", line 302, in download
    self.download_episode()
  File "crunchy-xml-decoder\ultimate.py", line 77, in download_episode
    html_page_resp = gethtml(self.page_url, return_form = 'respond')
  File "crunchy-xml-decoder\altfuncs.py", line 493, in gethtml
    res = session.get(url, params=req, headers=headers)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python38\lib\site-packages\cloudscraper\__init__.py", line 262, in request
    self.perform_request(method, url, *args, **kwargs)
  File "C:\Python38\lib\site-packages\cloudscraper\__init__.py", line 181, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 665, in send
    history = [resp for resp in gen]
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
Press any key to continue . . .

Not sure if it's the same issue.

**Comment by alzamer2** [comment]
are you using vpn?
the error say that cloudflare scraper tried many times

**Comment by reikitsune** [comment]
> 
> 
> are you using vpn? the error say that cloudflare scraper tried many times

I'm not currently, and Anti-virus is off to make sure too.

**Comment by alzamer2** [comment]
just tried downloading same episod 

>   ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
  │                                                                                                                  │
  │  CrunchyRoll Downloader Toolkit                                                                                  │
  │                                                                                                                  │
  │  If you don't have a premium account, go and sign up for one now. It's well worth it, and supports the animators.│
  │                                                                                                                  │
  │    1 - Download Anime                                                                                            │
  │    2 - Download Subtitle only                                                                                    │
  │    3 - Login                                                                                                     │
  │    4 - Login As Guest                                                                                            │
  │    5 - Download an entire Anime(Autocatch links)                                                                 │
  │    6 - Run Queue                                                                                                 │
  │                                                                                                                  │
  │                                                                                                                  │
  │    999 - Settings                                                                                                │
  │                                                                                                                  │
  │                                                                                                                  │
  │    000 - Exit                                                                                                    │
  │                                                                                                                  │
  └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
>>1
--------------------------
---- Start New Export ----
--------------------------
CrunchyRoll Downloader Toolkit DX v0.98b
Crunchyroll hasn't changed anything.

If you don't have a premium account, go and sign up for one now. It's well worth it, and supports the animators.

----------
Booting up...
Please enter Crunchyroll video URL:>
https://www.crunchyroll.com/digimon-ghost-game/episode-1-the-sewn-lip-man-816959
Now Downloading - Digimon Ghost Game Episode 1 - THE SEWN-LIP MAN [HLS stream]

                                                                                                        46.46MB                                                                                                        |    @ 11.30Mb/s
                                                                                                Part#17 [2.92MB/2.92MB]                                                                                                |% 100.0 @ 212.4Mb/s

and it worked just fine
can you retry download it again?

**Comment by alzamer2** [comment]
just finished downloading it (@1080p), so what about you?

**Comment by reikitsune** [comment]
I'm still having the same error. What version of python are you using?

**Comment by alzamer2** [comment]
i tested the code at 3.7 and 3.8
but it should work with 3.9+

what you version?

**Comment by alzamer2** [comment]
can you copy the full concel text? from start to error!!

**Comment by reikitsune** [comment]
Python Version=3.8.2 64 bit
OS Version=Windows 10 10.0.19041 SP0
System Type=AMD64
Code Version=1.4 rev.32 (Up-To-Date)
colorama : installed!
lxml : installed!
wget : installed!
cryptography.hazmat.primitives.ciphers : installed!
cloudscraper : installed!
m3u8 : installed!
youtube_dl : installed!
bs4 : installed!
pager : installed!
unidecode : installed!
socks : installed!
psutil : installed!
browser_cookie3 : installed!
MKVMERGE.EXE : Found!
FFMPEG.EXE : Found!
User Name = Crono_Flash
Membership Type = Premium
  ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
  │                                                                                                                  │
  │  CrunchyRoll Downloader Toolkit                                                                                  │
  │                                                                                                                  │
  │  If you don't have a {Green_c}premium{Default_c} account, go and sign up for one now. It's well worth it, and    │
  │      supports the animators.                                                                                     │
  │                                                                                                                  │
  │    1 - Download Anime                                                                                            │
  │    2 - Download Subtitle only                                                                                    │
  │    3 - Login                                                                                                     │
  │    4 - Login As Guest                                                                                            │
  │    5 - Download an entire Anime(Autocatch links)                                                                 │
  │    6 - Run Queue                                                                                                 │
  │                                                                                                                  │
  │                                                                                                                  │
  │    999 - Settings                                                                                                │
  │                                                                                                                  │
  │    000 - Exit                                                                                                    │
  │                                                                                                                  │
  └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
>>1
--------------------------
---- Start New Export ----
--------------------------
CrunchyRoll Downloader Toolkit DX v0.98b
Crunchyroll hasn't changed anything.

If you don't have a premium account, go and sign up for one now. It's well worth it, and supports the animators.

----------
Booting up...
Please enter Crunchyroll video URL:>
https://www.crunchyroll.com/digimon-ghost-game/episode-1-the-sewn-lip-man-816959
Traceback (most recent call last):
  File "crunchy-xml-decoder-py3.py", line 402, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 128, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 155, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "crunchy-xml-decoder-py3.py", line 134, in ultimate_
    ultimate_class.download(*arg,**kwarg)
  File "crunchy-xml-decoder\ultimate.py", line 302, in download
    self.download_episode()
  File "crunchy-xml-decoder\ultimate.py", line 77, in download_episode
    html_page_resp = gethtml(self.page_url, return_form = 'respond')
  File "crunchy-xml-decoder\altfuncs.py", line 493, in gethtml
    res = session.get(url, params=req, headers=headers)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python38\lib\site-packages\cloudscraper\__init__.py", line 262, in request
    self.perform_request(method, url, *args, **kwargs)
  File "C:\Python38\lib\site-packages\cloudscraper\__init__.py", line 181, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 665, in send
    history = [resp for resp in gen]
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
Press any key to continue . . .

**Comment by alzamer2** [comment]
wired
try using autocatch

**Comment by reikitsune** [comment]
Just tried it. Still the same error. I may just need to wait a little before I can use it.

**Comment by alzamer2** [comment]
try oening the link in browser,maybe your ip adress is cloudflare blacklist

**Comment by reikitsune** [comment]
link works in both firefox and chrome. And can play the episode at 1080p.

**Comment by Dokman** [comment]
In my case it worked your last fix, I've relogged my account and then download and it was working

**Comment by reikitsune** [comment]
I switched the link to the beta version, and tried to just download the subs and got a different error. It's still cloudflare, but it's about the recaptcha.

---- Downloading Subtitle ----

Please enter Crunchyroll video URL:
https://beta.crunchyroll.com/watch/G7PU4WE1V/the-sewn-lip-man
cloudscraper.exceptions.CloudflareReCaptchaProvider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.
Press any key to continue . . .

I even relogged in everytime, and get this consistently.

**Comment by alzamer2** [comment]
its seem your ip is really blacklisted at crunchyroll/cloudflare
is your ip fixed or it got changed every time you dial up/disconnect-reconnect with your isp?

**Comment by alzamer2** [comment]
ok i have good news and bad news about "requests.exceptions.TooManyRedirects: Exceeded 30 redirects." error

good news i found the cause
recently crunchy roll released beta site for new look
and you can go test it out at [beta.crunchyroll.com](http://beta.crunchyroll.com)
and here is bad news
any US user will forcly redirct to beta site and no mather what you cant use classic site
and as new site i need to rebuild scraping from zero so it will take sometime
ps: beta site use some complicated method to build its site and i needed 2hr just to find first string

**Comment by Dokman** [comment]
It Will happen in Europe too

**Comment by alzamer2** [comment]
damn , that meanss i better hurry up with fixing this issue

ps: us  proxy is down so its better to turn it off until it get fixed

**Comment by darkhelmet2016** [comment]
Tried that url and getting an error about the subs.

Traceback (most recent call last):
  File "crunchy-xml-decoder-py3.py", line 402, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 128, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 155, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "crunchy-xml-decoder-py3.py", line 134, in ultimate_
    ultimate_class.download(*arg,**kwarg)
  File "crunchy-xml-decoder\ultimate.py", line 311, in download
    vilos_subtitle(self.page_url)
  File "crunchy-xml-decoder\altfuncs.py", line 720, in vilos_subtitle
    html_page_ = gethtml(page_url_)
  File "crunchy-xml-decoder\altfuncs.py", line 493, in gethtml
    res = session.get(url, params=req, headers=headers)
  File "C:\Users\\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cloudscraper\__init__.py", line 239, in request
    super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "C:\Users\\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
Press any key to continue . . .

**Comment by alzamer2** [comment]
@darkhelmet2016 the problem is when classic site detects that you are in us or using USproxy it will redirect you to the beta site without asking

**Comment by darkhelmet2016** [comment]
Yea, saw your comment but thought would post it anyway so you would know about the sub line too since did not see it mentioned in the other users log.

**Comment by alzamer2** [comment]
ok i uploaded 1.4 rev.34
its support beta site
but it still need work so it can support us proxy and autocath

**Comment by darkhelmet2016** [comment]
Getting an error trying to use the downloader updater again.

trying to close Crunchyroll-XML-Decoder-py3.......
←[31mDownload failed←[0m, retry...1
←[31mDownload failed←[0m, retry...2
←[31mDownload failed←[0m, retry...3
←[31mDownload failed←[0m, retry...4
←[31mDownload failed←[0m, retry...5
Traceback (most recent call last):
  File ".\crunchy-xml-decoder\updater.py", line 183, in <module>
    run_update()
  File ".\crunchy-xml-decoder\updater.py", line 175, in run_update
    update.run()
  File ".\crunchy-xml-decoder\updater.py", line 158, in run
    Print(f'{Red_c}Update file was not downloaded{Default_c}, please try to download file manualy from "https://github.com/alzamer2/Crunchyroll-XML-Decoder-py3/tree/{self.github_branch}"')
NameError: name 'Print' is not defined
Press any key to continue . . .

**Comment by darkhelmet2016** [comment]
It is only downloading subs.

**Comment by Dokman** [comment]
@alzamer2 they applied to the beta website to EU
