### ISSUE TITLE
Code not working after update

### ISSUE THREAD

**Issue by alzamer2** [alzamer2/Crunchyroll-XML-Decoder-py3#5]
the latest update change file settings.ini structure 
so you need to delete the setting.ini first then run the code

**Comment by darkhelmet2016** [comment]
Noticed some of the files had python 36 and some had 36 still will those eventually be updated?

**Comment by darkhelmet2016** [comment]
Just checked a file with hard subs and it did not output in mkv but kept the file as ts. Show was added today. 
https://www.crunchyroll.com/goshogun/goshogun-the-time-etranger-goshogun-the-time-etranger-dub-784915

**Comment by alzamer2** [comment]
are you sure no error showed up?
and can you tell me more about what do you mean with 36?

**Comment by darkhelmet2016** [comment]
The __pycache__ folder left behind files like altfuncs.cpython-36 and also made a file named altfuncs.cpython-37 instead of getting rid of depreciated files, Not sure if this is what caused the file to not mux properly.

Crunchyroll hasn't changed anything.

If you don't have a premium account, go and sign up for one now. It's well worth
 it, and supports the animators.

----------
Booting up...

Now Downloading - GoShogun - GoShogun- The Time Etranger (Dub)
                         810MB/810MB                         |%100 @ 7.18Mb/s
                          Part#534                           |%100.0


------------------------------
---- Downloading Subtitle ----
------------------------------
The video has hardcoded subtitles.
Press any key to continue . . .

**Comment by alzamer2** [comment]
about altfuncs.cpython-36 and altfuncs.cpython-37 these are only compliled files for python you can ignot them
i forgot line for debug in code it should mux now after update
even though because its ts file it will work any way,
i fixed it and updated the code

**Comment by darkhelmet2016** [comment]
But one question is this program not decrypting subs right? A lot of them use formatting that does not seem to carry over like the bold outline they use for subs and when they use stylized subs with colors for screen text.

**Comment by alzamer2** [comment]
hmm, I don't understand what do you mean by "A lot of them use formatting that does not seem to carry over like the bold outline they use for subs and when they use stylized subs with colors for screen text."
if you mean compared to other fansubs the subtitle this program rip don't have styles, then you got the wrong idea
Crunchyroll even though they use ASS they use minimum styles in their subtitle:
* they don't sub oping/ending
* they don't use colors in subs
* they don't use drawing to cover the subs on labels
* etc
they used to encypt thier subtitle (and api system is still there) but when i rebuild the code i was suprised to find they no longer use api and they dirctly inject the decrypted subtitle link in html page (with video link too) so new code dont decrypt anything and dirctly download the subtile from page

**Comment by darkhelmet2016** [comment]
Actually they do use color in subs. https://www.crunchyroll.com/the-rising-of-the-shield-hero Also you never noticed the big black border around their subs? on their apps and on their streams on the episode pages? That is formatting. Download some of the rips from HS.  There is like a 2-3 in black border around their subs from when they rip CR shows. They use color subs in some shows to match what is on the screen text in Japanese what is translated.

**Comment by darkhelmet2016** [comment]
See you closed this without addressing the issue of the formatting and the fonts. When HS was doing shows they made sure that the fonts were also included in the files.
