### ISSUE TITLE
Download error downloading hard subbed show in Japanese

### ISSUE THREAD

**Issue by darkhelmet2016** [alzamer2/Crunchyroll-XML-Decoder-py3#7]
Got this error trying to download http://www.crunchyroll.com/captain-harlock-arcadia-of-my-youth-endless-orbit-ssx

----------
Booting up...

Traceback (most recent call last):
  File "C:\Users\Owner\Downloads\Crunchyroll-XML-Decoder-py3-master (6)\crunchy-
xml-decoder-py3.py", line 407, in <module>
    make_choise()
  File "C:\Users\Owner\Downloads\Crunchyroll-XML-Decoder-py3-master (6)\crunchy-
xml-decoder-py3.py", line 374, in make_choise
    queueu(os.path.join('.','queue.txt'))
  File "C:\Users\Owner\Downloads\Crunchyroll-XML-Decoder-py3-master (6)\crunchy-
xml-decoder-py3.py", line 127, in queueu
    ultimate(line.rstrip('\n'), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 121, in ultimate
    hls_url = stream_url[None]
KeyError: None
Press any key to continue . . .

**Comment by alzamer2** [comment]
i think i fixed it
test it out

**Comment by darkhelmet2016** [comment]
Working on this one, will have to try some other of their shows later when this is done downloading this series to check.

**Comment by alzamer2** [comment]
ok, if there is no problem at this point close the issue as i'm logging out and need like 12hr to log in again

**Comment by darkhelmet2016** [comment]
Ok, seems to be working for now so will close it out.
